spring:
  datasource:
    url: ${DATABASE_URL:}
    username: ${USERNAME:}
    password: ${PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 2000


JWT_SECRET_KEY: ${JWT_SECRET_KEY:}